### ISSUE TITLE
[Android Auto] Crash Remote setSurfaceListener call failed

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android-examples#31]
https://github.com/mapbox/mapbox-navigation-android-examples/issues/27 We're accepting all hosts, so it's bizarre this fails to connect to a host 🤔 

Google issue tracker here https://issuetracker.google.com/issues/196441767

```
Fatal Exception: java.lang.RuntimeException: androidx.car.app.HostException: Remote setSurfaceListener call failed
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:154)
       at androidx.car.app.utils.-$$Lambda$RemoteUtils$GPy0HpPmjwPYOTu96sesXaP1QcU.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
Caused by androidx.car.app.HostException: Remote setSurfaceListener call failed
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:92)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHost(RemoteUtils.java:105)
       at androidx.car.app.HostDispatcher.dispatch(HostDispatcher.java:97)
       at androidx.car.app.AppManager.setSurfaceCallback(AppManager.java:64)
       at com.mapbox.androidauto.car.map.CarMapSurfaceLifecycle.onCreate(CarMapSurfaceLifecycle.java:37)
       at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
       at com.mapbox.androidauto.car.map.CarMapSurfaceService.<init>(CarMapSurfaceService.java:36)
       at com.mapbox.onetap.androidauto.car.MainCarSession$onCreateScreen$1.invokeSuspend(MainCarSession.java:34)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.mapbox.onetap.androidauto.car.MainCarSession.onCreateScreen(MainCarSession.java:30)
       at androidx.car.app.CarAppService$1.lambda$onAppCreate$0(CarAppService.java:378)
       at androidx.car.app.-$$Lambda$CarAppService$1$Pm8b87Y2y5REJKLNfuPOf4oHVls.dispatch(-.java:8)
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:149)
       at androidx.car.app.utils.-$$Lambda$RemoteUtils$GPy0HpPmjwPYOTu96sesXaP1QcU.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

```
Caused by androidx.car.app.HostException: Remote getHost(App) call failed
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:92)
       at androidx.car.app.HostDispatcher.getHost(HostDispatcher.java:147)
       at androidx.car.app.HostDispatcher.lambda$dispatch$1(HostDispatcher.java:98)
       at androidx.car.app.-$$Lambda$HostDispatcher$pdyqPaHw3n_U2eDb2IKsW6pWg7o.call(-.java:8)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHostForResult(RemoteUtils.java:86)
       at androidx.car.app.utils.RemoteUtils.dispatchCallToHost(RemoteUtils.java:105)
       at androidx.car.app.HostDispatcher.dispatch(HostDispatcher.java:97)
       at androidx.car.app.AppManager.setSurfaceCallback(AppManager.java:64)
       at com.mapbox.androidauto.car.map.CarMapSurfaceLifecycle.onCreate(CarMapSurfaceLifecycle.java:37)
       at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
       at com.mapbox.androidauto.car.map.CarMapSurfaceService.<init>(CarMapSurfaceService.java:36)
       at com.mapbox.onetap.androidauto.car.MainCarSession$onCreateScreen$1.invokeSuspend(MainCarSession.java:34)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.mapbox.onetap.androidauto.car.MainCarSession.onCreateScreen(MainCarSession.java:30)
       at androidx.car.app.CarAppService$1.lambda$onAppCreate$0(CarAppService.java:378)
       at androidx.car.app.-$$Lambda$CarAppService$1$Pm8b87Y2y5REJKLNfuPOf4oHVls.dispatch(-.java:8)
       at androidx.car.app.utils.RemoteUtils.lambda$dispatchCallFromHost$0(RemoteUtils.java:149)
       at androidx.car.app.utils.-$$Lambda$RemoteUtils$GPy0HpPmjwPYOTu96sesXaP1QcU.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by kmadsen** [comment]
Closing this because we are upgraded to 1.1 and the issue tracker also says the issue was fixed there
